_format_version: "2.1"
_transform: true

services:
  - name: auth-service
    host: auth-service.service.consul
    connect_time: 60000
    protocol: http
    read_timeout: 60000
    port: 0
    path: "/"
    retries: 5
    write_timeout: 60000
    routes:
      - name: auth-route
        path:
          - /api/v1/auth
        protocol:
          - http
          - https
