version: "3"

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    # ports:
    #   - 5832:5432
    environment:
      POSTGRES_USER: ${KONG_DB_USERNAME}
      POSTGRES_DB: ${KONG_DB_NAME}
      POSTGRES_PASSWORD: ${KONG_DB_PASSWORD}
    networks:
      taxnet-net:
        ipv4_address: 192.168.18.2
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  kong-migrations:
    image: kong:2.8.1-alpine
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: 192.168.18.2
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_DATABASE: ${KONG_DB_NAME:-kong}
    command: kong migrations bootstrap
    restart: on-failure
    networks:
      - taxnet-net
    depends_on:
      - kong-database

  kong:
    image: kong:latest
    container_name: kong
    environment:
      LC_CTYPE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      KONG_DATABASE: postgres
      KONG_PG_HOST: 192.168.18.2
      KONG_PG_DATABASE: ${KONG_DB_NAME:-kong}
      KONG_PG_USER: ${KONG_DB_USERNAME}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_DNS_RESOLVER: ${KONG_DNS_RESOLVER}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    ports:
      - ${KONG_PROXY_PORT}:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    links:
      - kong-database:kong-database
    networks:
      - taxnet-net
    depends_on:
      - kong-migrations

  konga:
    image: pantsel/konga
    ports:
      - 1337:1338
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=develop
    networks:
      - taxnet-net

volumes:
  db-data-kong-postgres:


networks:
  taxnet-net:
    driver: bridge
    name: taxnet-net
    ipam:
      config:
        - subnet: 192.168.18.0/24
          gateway: 192.168.18.1
